### PR TITLE
feat(ingress-secrets-services): add ingress, secrets and services listing page

### PR DESCRIPTION
**Pull request by abdelrahmanahmed**
This PR is created to add ingress and services listing pages and create/delete action, here is what it looks like:

 ### Services
image

services

###  Ingress
image

ingress

### CODE REVIEW

**Comment by ragoob** [comment]
Please rebase and fix merge conflicts

**Comment by abdelrahmanahmed** [comment]
> Please rebase and fix merge conflicts

Done and fixed a conflict in the shared module

**Comment by abdelrahmanahmed** [comment]
added permissions to ingress and services

**Comment by abdelrahmanahmed** [comment]
I added secrets here as well

image

**Pull request merged**
